<?php
/**
 * Source: http://magento-zend.blogspot.com/2011/12/adding-show-hide-more-functionality-in.html
 */
/* embedded to the plugin's code
  $displaySize = 2;
  $i = 0;
  $filterName = strtolower($this->getName());
  $cnt = count($this->getItems());
  ?>

  <ol class="wts-showmore">
  <?php foreach ($this->getItems() as $_item): ?>
  <?php if ($i == $displaySize) { ?>
  <div id="more-<?php echo $filterName ?>"><a>Show more</a></div>
  <div id="cont-<?php echo $filterName ?>">
  <?php } ?>
  <li>
  <?php if ($_item->getCount() > 0): ?>
  <a href="<?php echo ($_item->isSelected()) ? $_item->getRemoveUrl() : $_item->getUrl() ?>">
  <input type="checkbox"<?php if ($_item->isSelected()): ?> checked="checked" <?php endif; ?>/>
  <?php echo $_item->getLabel() ?>
  <?php if ($this->shouldDisplayProductCount()): ?>
  <span class="count">(<?php echo $_item->getCount() ?>)</span>
  <?php endif; ?>
  </a>
  <?php else: ?>
  <span>
  <?php echo $_item->getLabel(); ?>
  <?php if ($this->shouldDisplayProductCount()): ?>
  <span class="count">(<?php echo $_item->getCount() ?>)</span>
  <?php endif; ?>
  </span>
  <?php endif; ?>
  <?php
  $i++;
  if ($i == $cnt && $cnt > $displaySize)
  echo '<div id="less-' . $filterName . '"><a >Show less</a></div></div>';
  ?>
  </li>
  <?php endforeach ?>
  </ol>
 * 
 */

//directly pasted below the code from source
?>
<ol class="wts-showmore-filter">
    <?php
    $displaySize = 1;
    $i = 0;
    $filterName = strtolower($this->getName());
    $cnt = count($this->getItems());
    foreach ($this->getItems() as $_item):
        ?>
        <?php if ($i == $displaySize) { ?>
            <div id="more-<?php echo $filterName ?>"><a >Show Filter</a></div>
            <div id="cont-<?php echo $filterName ?>">
            <?php } ?>
            <li>
                <?php if ($_item->getCount() > 0): ?>
                    <a href="<?php echo $this->urlEscape($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>
                <?php else: echo $_item->getLabel() ?>
                <?php endif; ?>
                (<?php echo $_item->getCount() ?>)
            </li>
            <?php
            $i++;
            if ($i == $cnt && $cnt > $displaySize)
                echo '<div id="less-' . $filterName . '"><a >Hide Filter</a></div></div>';
            ?>
        <?php endforeach ?>
</ol>